---
- name: Installs the MySQL server
  block:
  - name: Installing the MySQL server
    apt: 
      name: "{{ item }} "
      state: present
      update_cache: yes
    with_items:
      - mysql-server
      - python3-pymysql
    notify:
    - start-db

# MySQL Configuration
## Update the Root Password
  - name: Sets the root password
    mysql_user:
      name: root
      password: "{{ MYSQL_ROOT_PWD }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock
    notify:
    - restart-db
  when: CREATE_DB_SERVER == True
  tags:
    - never
    - create-db-server
    - install-all
## Create the database
#- name: Create the database
#  mysql_db:
#    name: "{{ MYSQL_DB_NAME }}"
#    state: present
#  become: yes

#- name: Create user database
#  mysql_user:
#    name: "{{ MYSQL_DB_USER }}"
#    password: "{{ MYSQL_DB_PASSWORD }}"
#    priv: '*{{ MYSQL_DB_NAME }}*:ALL,GRANT'
#    state: present
#  become: yes

# Import DB
- name: Create DB Objects
  block:
  - name: copying the SQL file
    template:
      src: "objects.sql"
      dest: "{{ DB_HOME}}/objects.sql"

  - name: Creating the DB Objects
    shell: "/usr/bin/mysql -u root --password={{ MYSQL_ROOT_PWD }} <objects.sql"
    args:
      chdir: "{{ DB_HOME }}"
  tags:
    - never
    - import-db
    - install-all
